version: '3.8'

services:
  bot:
    build: .
    restart: always
    env_file: .env
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data:
